### ISSUE TITLE
make Error

### ISSUE THREAD

**Issue by cn0xroot** [chrisfu/homebrew-tap#3]
Hi，nice to talk with you. when i install proxmake3 with brew:
```
➜  ~ sudo brew install --HEAD proxmark3
Error: Formulae found in multiple taps:
 * chrisfu/proxmark3/proxmark3
 * chrisfu/tap/proxmark3

Please use the fully-qualified name e.g. chrisfu/proxmark3/proxmark3 to refer the formula.
➜  ~ sudo brew install chrisfu/proxmark3/proxmark3
➜  ~ sudo brew install chrisfu/proxmark3/proxmark3
Warning: You are using OS X 10.12.
We do not provide support for this pre-release version.
You may encounter build failures or other breakage.
==> Installing proxmark3 from chrisfu/homebrew-proxmark3
==> Downloading https://github.com/Proxmark/proxmark3/archive/v2.3.0.tar.gz
Already downloaded: /Library/Caches/Homebrew/proxmark3-2.3.0.tar.gz
==> make -C client/hid-flasher/
==> make all clean
./stdint.h:21:24: note: previous declaration of 'uint32_t' was here
 typedef unsigned int   uint32_t;
                        ^
make[1]: *** [obj/start.o] Error 1
make: *** [armsrc/all] Error 2
Warning: It appears you have MacPorts or Fink installed.
Software installed with other package managers causes known problems for
Homebrew. If a formula fails to build, uninstall MacPorts/Fink and try again.

READ THIS: https://git.io/brew-troubleshooting
If reporting this issue please do so at (not Homebrew/homebrew):
  https://github.com/chrisfu/homebrew-proxmark3/issues

/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:353:in `open_http': 422 Unprocessable Entity (GitHub::Error)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:709:in `buffer_open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:210:in `block in open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `catch'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:208:in `open_loop'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:149:in `open_uri'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:689:in `open'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/open-uri.rb:30:in `open'
	from /usr/local/Library/Homebrew/utils.rb:436:in `open'
	from /usr/local/Library/Homebrew/utils.rb:466:in `issues_matching'
	from /usr/local/Library/Homebrew/utils.rb:498:in `issues_for_formula'
	from /usr/local/Library/Homebrew/exceptions.rb:209:in `fetch_issues'
	from /usr/local/Library/Homebrew/exceptions.rb:205:in `issues'
	from /usr/local/Library/Homebrew/exceptions.rb:248:in `dump'
	from /usr/local/Library/brew.rb:160:in `rescue in <main>'
	from /usr/local/Library/brew.rb:67:in `<main>'
```
what should i do to fix it? thank you.

**Comment by cn0xroot** [comment]
OS X Version:10.12.3

**Comment by chrisfu** [comment]
Hi,

Firstly, removed the old tap. With it there you'd never know exactly what
might be happening.

Secondly, you've installed with `--HEAD` but it's trying to install via the
broken Tarball and therefore ignoring your use of the HEAD flag. That's odd
and not something I've seen before.

I'll check on my Mac a bit later and see if I can reproduce.

Chris

On 24 Feb 2017 06:23, "cn0xroot" <notifications@github.com> wrote:

OS X Version:10.12.3

—
You are receiving this because you are subscribed to this thread.
Reply to this email directly, view it on GitHub
<https://github.com/chrisfu/homebrew-tap/issues/3#issuecomment-282214645>,
or mute the thread

**Comment by cn0xroot** [comment]
thanks for replay

**Comment by cn0xroot** [comment]
bug fix when i update brew,but can't use sudo brew:
```

brew install proxmark3
Updating Homebrew...
Error: Formulae found in multiple taps:
 * chrisfu/proxmark3/proxmark3
 * chrisfu/tap/proxmark3

Please use the fully-qualified name e.g. chrisfu/proxmark3/proxmark3 to refer the formula.
➜  ~ brew install chrisfu/proxmark3/proxmark3
==> Installing proxmark3 from chrisfu/proxmark3
==> Installing dependencies for chrisfu/proxmark3/proxmark3: libusb, pkg-config, wget
==> Installing chrisfu/proxmark3/proxmark3 dependency: libusb
==> Using the sandbox
==> Downloading https://github.com/libusb/libusb/releases/download/v1.0.21/libusb-1.0.21.tar.bz2
Already downloaded: /Users/Good-Soon/Library/Caches/Homebrew/libusb-1.0.21.tar.bz2
Error: Permission denied - /Users/Good-Soon/Library/Logs/Homebrew/libusb/00.options.out

➜  ~ sudo !!
➜  ~ sudo brew install chrisfu/proxmark3/proxmark3
Password:
Error: Running Homebrew as root is extremely dangerous and no longer supported.
As Homebrew does not drop privileges on installation you would be giving all
build scripts full access to your system.
```
